spring:
      datasource:
                url: jdbc:mysql://localhost:3306/dept
                driver-class-name: com.mysql.cj.jdbc.Driver
                username: root
                password: root
      jpa:
         hibernate:
           ddl-auto: update
         show-sql: true
         properties:
           hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect 
             
logging:
 level:
  root: INFO
 file:
  name:  mylogs.log